name: Checks
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install black pylint mypy
    - run: black --diff --check $(git ls-files '*.py')
    - run: pylint --disable=W $(git ls-files '*.py')
    - run: mypy --strict --allow-empty-bodies $(git ls-files '*.py')